---
- name: Search for metering resources
  community.kubernetes.k8s_info:
    api_version: v1
    kind: MeteringConfig
    namespace: "{{ namespace }}"
  register: metering_objects

- name: Ensure metering has been configured
  fail:
    msg: 'Metering has not been configured.'
  when: not metering_objects.resources

- name: Obtain cost-mgmt-setup info
  community.kubernetes.k8s_info:
    api_version: cost-mgmt.openshift.io/v1alpha1
    kind: CostManagement
    namespace: "{{ namespace }}"
    name: cost-mgmt-setup
  register: cost_mgmt_setup

- name: Set current_day
  set_fact:
    current_day: "{{ cost_mgmt_setup.resources[0].spec.current_day | int }}"
  when: cost_mgmt_setup.resources
  ignore_errors: true

- name: Set current_month
  set_fact:
    current_month: "{{ cost_mgmt_setup.resources[0].spec.current_month | int }}"
  when: cost_mgmt_setup.resources
  ignore_errors: true

- name: Set current_year
  set_fact:
    current_year: "{{ cost_mgmt_setup.resources[0].spec.current_year | int }}"
  when: cost_mgmt_setup.resources
  ignore_errors: true

- name: Get cost_mgmt_data_cr
  community.kubernetes.k8s_info:
    api_version: cost-mgmt-data.openshift.io/v1alpha1
    kind: CostManagementData
    namespace: "{{ namespace }}"
    name: cost-mgmt-data-example
  register: cost_mgmt_data_cr
  ignore_errors: true

- name: Set cost_mgmt_data_cr_exists
  set_fact:
    cost_mgmt_data_cr_exists: "{{ cost_mgmt_data_cr.resources | bool }}"

# - name: Set cost_mgmt_data_cr_exists
#   set_fact:
#     cost_mgmt_data_cr_exists: false
#   when: not cost_mgmt_data_cr.resources

- name: The current month reports are created for
  operator_sdk.util.k8s_status:
    api_version: cost-mgmt.openshift.io/v1alpha1
    kind: CostManagement
    name: cost-mgmt-setup
    namespace: "{{ namespace }}"
    status:
        current_reporting_month: "{{ current_month }}"
        cost_mgmt_data_cr_exists: "{{ cost_mgmt_data_cr_exists }}"

- name: Create datasources and reportqueries
  community.kubernetes.k8s:
    namespace: "{{ namespace }}"
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "files/cm*"

- name: Manage current month reports
  import_tasks: reports.yml
  vars:
    input_month: '{{ current_month }}'
    input_year: '{{ current_year }}'
    month_delta: 0
    state: 'present'

- name: Manage next month reports
  import_tasks: reports.yml
  vars:
    input_month: '{{ current_month }}'
    input_year: '{{ current_year }}'
    month_delta: 1
    state: 'present'
  when: (current_day | int)  > 24

- name: Manage previous month reports
  import_tasks: reports.yml
  vars:
    input_month: '{{ current_month }}'
    input_year: '{{ current_year }}'
    month_delta: -1
    state: 'absent'
  when: (current_day | int)  < 3
